version: "3.9"

networks:
  hiddn-lb-default-network:

volumes:
  hiddn-lb-default-volume: {}
  
services:
  kong-database:
    image: postgres:9.6
    restart: on-failure
    volumes:
      - hiddn-lb-default-volume:/var/lib/postgresql/data
    networks:
      - hiddn-lb-default-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hiddn-lb-database
      POSTGRES_USER: hiddn-database
      POSTGRES_PASSWORD: hiddn-lb-localhost-pwd
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 45s
      timeout: 30s
      retries: 3

  kong:
    image: hiddn-lb-default-oidc
    restart: on-failure
    depends_on:
      - kong-database
    networks:
      - hiddn-lb-default-network
    ports:
      - "8000:8000" # For Listener
      - "8001:8001" # For Admin API
      - "8443:8443" # For Listener (SSL only)
      - "8444:8444" # For Admin API (SSL only)
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: hiddn-lb-database
      KONG_PG_USER: hiddn-database
      KONG_PG_PASSWORD: hiddn-lb-localhost-pwd
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PLUGINS: oidc 
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10